### ISSUE TITLE
Oxford comma check?

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/retext-preset-wooorm#1]
Not sure if this is already in here or not - but was curious if you already did this somewhere else?

**Comment by wooorm** [comment]
It’s cool, but you can’t do it programmatically I think (that’s why you need it!): https://www.buzzfeed.com/adamdavis/the-oxford-comma-is-extremely-important-and-everyone-should

**Comment by wooorm** [comment]
I think it’s impossible. If you don’t a free, PRs and plugins are welcome.
