### ISSUE TITLE
Add retext-passive

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/retext-preset-wooorm#2]
I’ve seen you reference [retext-passive](https://github.com/retextjs/retext-passive) in various of my pull requests for projects using this preset. However, it’s not actually used. I suggest to add it here, so tooling will warn about it instead of spending time to write GitHub comments on this.

**Comment by wooorm** [comment]
It has too many false positives to be used on all prose unfortunately.
For a more strict natural language set, see: https://github.com/unifiedjs/unifiedjs.github.io/blob/9df7aa49af124ecf408e29f17030357049184f90/.remarkrc.js#L27-L37. The rules are pretty useful. But it’s too slow to be used everywhere.
